version: "3.9"
services:
  windows:
    command: python3 example.py
    build: .
    volumes:
      - ./src:/src
      - /run/desktop/mnt/host/wslg/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=:0
  linux:
    command: python3 example.py
    build: .
    volumes:
      - ./src:/src
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
    security_opt:
      - "label=type:container_runtime_t"