# configuring docker containers for wsl explained here:
# https://github.com/microsoft/wslg/blob/main/samples/container/Containers.md
# to run from windows some paths must be replaced with /run/desktop/mnt/host/wslg

# for dev within container use wsl service with instructions from:
# https://learn.microsoft.com/en-us/windows/wsl/tutorials/wsl-containers

version: "3.9"
services:
  windows:
    command: pnpm run start
    build: .
    volumes:
      - .:/project
      # X11
      - /run/desktop/mnt/host/wslg/.X11-unix:/tmp/.X11-unix
      # Wayland / PulseAudio
      - /run/desktop/mnt/host/wslg:/mnt/wslg
    environment:
      # X11
      - DISPLAY=:0
      # Wayland
      - WAYLAND_DISPLAY=wayland-0
      - XDG_RUNTIME_DIR=/mnt/wslg/runtime-dir
      # PulseAudio
      - PULSE_SERVER=/mnt/wslg/PulseServer
  wsl:
    command: pnpm run start
    build: .
    volumes:
      - .:/project
      # X11
      - /tmp/.X11-unix:/tmp/.X11-unix
      # Wayland / PulseAudio
      - /mnt/wslg:/mnt/wslg
    environment:
      # X11
      - DISPLAY=$DISPLAY
      # Wayland
      - WAYLAND_DISPLAY=$WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR
      # PulseAudio
      - PULSE_SERVER=$PULSE_SERVER
  linux:
    command: pnpm run start
    build: .
    volumes:
      - .:/project
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
    security_opt:
      - "label=type:container_runtime_t"
