- name: Set up AEAS
  hosts: localhost
  connection: local
  tasks:
    - name: Download Node.JS installer
      ansible.builtin.get_url:
        url: https://deb.nodesource.com/setup_18.x
        dest: /tmp/install_node.sh

    - name: Run Node.JS installer
      become: yes
      ansible.builtin.shell:
        cmd: cat /tmp/install_node.sh | bash

    - name: Install Node.JS
      become: yes
      ansible.builtin.apt:
        name: nodejs

    - name: Install Chromium (Electron dependencies)
      become: yes
      ansible.builtin.apt:
        name: chromium

    - name: Install TSK
      become: yes
      ansible.builtin.apt:
        name: sleuthkit

    - name: Install XXD
      become: yes
      ansible.builtin.apt:
        name: xxd

    - name: Download yq binary and make it executable
      become: yes
      ansible.builtin.get_url:
        url: https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
        dest: /usr/bin/yq
        mode: '0755'  # Set the file mode to make it executable

    - name: Install dmg2raw
      become: yes
      ansible.builtin.apt:
        name: dmg2raw

    - name: Install TestDisk dependencies
      become: yes
      ansible.builtin.apt:
        name:
          - build-essential
          - e2fslibs-dev
          - libewf-dev
          - libncurses5-dev
          - libncursesw5-dev
          - ntfs-3g-dev
          - libjpeg-dev
          - uuid-dev
          - zlib1g-dev
          - qtbase5-dev
          - qttools5-dev-tools
          - pkg-config
          - dh-autoreconf
          - git

    - name: Clone TestDisk repo
      ansible.builtin.git:
        repo: https://git.cgsecurity.org/testdisk.git
        dest: /tmp/testdisk

    - name: Create TextDisk config folder
      file:
        path: /tmp/testdisk/config
        state: directory

    - name: Generate TestDisk configuration
      command: autoreconf --install -W all -I config /tmp/textdisk/config
      args:
        chdir: /tmp/testdisk

    - name: Configure TestDisk
      command: ./configure
      args:
        chdir: /tmp/testdisk

    - name: Build and install TestDisk
      command: make install
      args:
        chdir: /tmp/testdisk
