- name: Set up AEAS dev
  hosts: localhost
  connection: local
  tasks:
    - name: Download Node.JS installer
      ansible.builtin.get_url:
        url: https://deb.nodesource.com/setup_18.x
        dest: /tmp/install_node.sh

    - name: Run Node.JS installer
      become: yes
      ansible.builtin.shell:
        cmd: cat /tmp/install_node.sh | bash

    - name: Install Node.JS
      become: yes
      ansible.builtin.apt:
        name: nodejs

    - name: Install Chromium (Electron dependencies)
      become: yes
      ansible.builtin.apt:
        name: chromium

    - name: Install TSK
      become: yes
      ansible.builtin.apt:
        name: sleuthkit

    - name: Install XXD
      become: yes
      ansible.builtin.apt:
        name: xxd
        
    - name: Download yq binary and make it executable
      become: yes
      ansible.builtin.get_url:
        url: https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
        dest: /usr/bin/yq
        mode: '0755'  # Set the file mode to make it executable

    - name: Install testdisk
      become: yes
      ansible.builtin.apt:
        name: testdisk

    # These are technically optional but make development a whole lot easier

    - name: Install Git
      become: yes
      ansible.builtin.apt:
        name: git

    - name: Download GitHub CLI archive keyring
      become: yes
      ansible.builtin.get_url:
        url: "https://cli.github.com/packages/githubcli-archive-keyring.gpg"
        dest: "/usr/share/keyrings/githubcli-archive-keyring.gpg"
        mode: "0644"

    - name: Add GitHub CLI to repos
      become: yes
      ansible.builtin.copy:
        content: "deb [arch=amd64 signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main\n"
        dest: /etc/apt/sources.list.d/github-cli.list
        mode: '0644'

    - name: Install GitHub CLI
      become: yes
      ansible.builtin.apt:
        name: gh
        update_cache: yes


